name: Gtb test all
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - name: Build with NPM
        run: |
          npm install
          npm run e2e
      - if: ${{ success() }}
        run: echo "TEST_RESULT=true" >> $GITHUB_ENV
      - if: ${{ failure() }}
        run: echo "TEST_RESULT=false" >> $GITHUB_ENV
      - if: ${{ always() }}
        run: |
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d/ -f2)
          curl -X POST "${{ secrets.DASHBOARD_ADDRESS }}/terms/${{ secrets.STUDENT_TERM }}/submissions/test?assignmentKey=${PROJECT_NAME}&gtbUsername=${{ secrets.STUDENT_NAME }}" \
              -H "Content-Type: application/json" \
              -u user:${{ secrets.SONAR_TOKEN }} \
              -d "${TEST_RESULT}"


