name: gtb sonar
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sonar:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
      - name: Cache sonar scanners
        id: cache-sonar-scanners
        uses: actions/cache@v2
        env:
          cache-name: cache-sonar-scanners
        with:
          path: ~/.sonar
          key: ${{ runner.os }}-sonar-scanner-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-sonar-scanner-
      - name: Download sonar scanners
        if: steps.cache-sonar-scanners.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
            repository: tws-graduate-program/sonar-scanner
            path: .sonar
      - name: Move sonar scanner
        if: steps.cache-sonar-scanners.outputs.cache-hit != 'true'
        run: mv .sonar ~
      - name: prepare gradle env
        run: |
          mkdir ~/.gradle && touch ~/.gradle/gradle.properties
          {
            echo "systemProp.gtb.sonar.host.url=${{ secrets.SONAR_ADDRESS }}"
            echo "systemProp.gtb.sonar.login=${{ secrets.SONAR_TOKEN }}"
            echo "systemProp.gtb.sonar.student.term=${{ secrets.STUDENT_TERM }}"
            echo "systemProp.gtb.sonar.student.name=${{ secrets.STUDENT_NAME }}"
          } > ~/.gradle/gradle.properties
          npm install sonar-scanner
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm run sonarqube || true



